### ISSUE TITLE
Is there a new feature to change or update the gogoanime URL in Binaries SenPY?

### ISSUE THREAD

**Issue by candrapersada** [FireHead90544/SenPY#16]
Is there a new feature to change or update the gogoanime URL in Binaries without waiting for a very long time?

**Comment by Arctic4161** [comment]
@candrapersada That feature has not been implemented. Right now it should auto pull the domain from our github action that auto pulls the domain every Sunday.

**Comment by candrapersada** [comment]
I hope the feature is implemented without install python and create `dist`
https://github.com/FireHead90544/SenPY/releases

**Comment by FireHead90544** [comment]
@candrapersada as Josh mentioned, due to some ISP limitations, we haven't implemented it on the client side. But we do have implemented a fix for that. There's a GitHub action that automatically updates the current gogoanime url in this repository. That action runs every Sunday's at midnight, or when we manually run it. The client simply fetches the current url from there.That way you won't need to wait too long for it to get updated to download a new binary as the values aren't hardcoded now starting from v1.2.0.
