### ISSUE TITLE
why the video name doesn't match?

### ISSUE THREAD

**Issue by candrapersada** [FireHead90544/SenPY#3]
why doesn't the name of the video match for example Majin Bone Episode 3 but what appears is only EP.3

**Comment by FireHead90544** [comment]
Because with animes with long name it will be pretty annoying and hard to read the name.
Just for the sake of user-friendlyness
It creates a folder named as the name of actual anime and just keep the episode number in the actual name of episode.

Example
`EP.1.mp4`, `EP.2.mp4`, `...` will be present inside the `Majin Bone`.
You can change this behaviour from the code.

**Comment by FireHead90544** [comment]
Pretty self explanatory, don't feel the need to change this behaviour. Re-open this issue if you have any other query.
